### ISSUE TITLE
Like by Location?

### ISSUE THREAD

**Issue by inhaletime** [nickpettican/InstaBot#11]
Hello,
How does the like function work? Is a like by location feature able to be implemented?

**Comment by nickpettican** [comment]
I'm afraid not @inhaletime, it works the same way the desktop Instagram website does.

For example: if you want to like *holiday* posts you get the top 12 from the most recent section here https://www.instagram.com/explore/tags/holiday/. Since there is no URL parameter that gives you posts by location (that I know of) this is not possible at the moment.

**Comment by inhaletime** [comment]
Can it be filtered?

searches hashtag > filters everything out that isnt Los Angeles > likes remaining photos

There would be a need of popular hashtags or alot of them?

**Comment by nickpettican** [comment]
It could, some posts include their location. But only some. 
It'll be a case of including lots of popular tags like "#happy" or "#love" and lowering the number of likes per day to make sure you get new posts every time you refresh the tag page. Otherwise Instabot will keep trying to fill the `bucket` with no success.
