### ISSUE TITLE
Can't find friends on news feed

### ISSUE THREAD

**Issue by inhaletime** [nickpettican/InstaBot#16]
I have added my following to the friends.csv file but i dont think its working. 

[ 2017-08-10 22:20:14 ] Scrolling through feed for friend's posts...  found 24, 0 from friends.

What feed is it scrolling through?

**Comment by nickpettican** [comment]
Hi @inhaletime,
The bot is scrolling through your news feed, the same one you get if you go to instagram.com or on your instagram app in your phone. 
It will find around 24 posts every time. If the users you included in your `friends.csv` file appear it will like their posts, if it's **0** this means that **the first 24 posts it has found do not include any from your friends list**.
This feature was made to like "friends" posts whenever they posted something new. If these users only post once a week then you'll get 0 until one of them posts something new.

**Comment by inhaletime** [comment]
I added all my followings to the friends.csv and have had it running all night. Im still not seeing it liking any posts. it should be liking every new post in my newsfeed? every username is on its own line in the .csv

**Comment by nickpettican** [comment]
That's odd, it seems to be working fine with me. Check for the following (you can tick the checkboxes once you did 👍):
- [ ] When it says `Checking the profiles of those you follow:` does it print usernames that are in your `friends.csv` file?
- [ ] Go to your newsfeed on your phone or computer and look at the first 24 posts and unlike them all (if they are liked), then include their usernames in `friends.csv` and run the bot. Can it still not find them?

For the stats, the bot will try to perform an operation when it is next due. In the case of liking the feed, it does so every hour. If there aren't any new posts it skips it and will try again the next hour but will add a count to `Current daily count: Like news feed: +1`. This is to avoid operations piling up - because if they do and you have a high number and they happen all at once Instagram could ban you.

Let me know how it goes!

**Comment by nickpettican** [comment]
Closing this, feel free to re-open if the issue continues!
