### ISSUE TITLE
Bot not starting ("out of hours")

### ISSUE THREAD

**Issue by n0ise** [nickpettican/InstaBot#33]
Hello, 
i'm trying to run your script into my raspberry, but it always says "Out of hours... sleeping until ", no matter if I change the hour to the near future (waiting couple of minutes to let it start) or in the past.

I've checked the date/time of my Pi, and it's showing the correct time (Timezone Europe)

edit: If i change the timezone to "Etc (GMT+1)" it works, so apparently when moving my timezone from the config, to Europe, it won't check the time (?!)

**Comment by eliareutlinger** [comment]
Have you tried to set the beginning end ending hours to the same value? In this case it should always run without sleeping.

I had the same problem with the sleeping-times and for me it was because the tool uses the unix epoch timestamp from UTC +0 and it doesn't matter what timezone you have set on your raspberry.

I fixed this myself and commited. So if this commit gets merged it should be working for you.

**Comment by n0ise** [comment]
Thanks, same start/end time does the trick. Waiting for the merge/fix :) 
Thank you

**Comment by nickpettican** [comment]
Merged, thanks @eliareutlinger !
