### ISSUE TITLE
Instagram's sharedData object changed

### ISSUE THREAD

**Issue by eliareutlinger** [nickpettican/InstaBot#36]
I don't know why this happens but since 2 days I can't use the bot anymore. Everytime I start the bot, it just gives me the following output:

![image](https://user-images.githubusercontent.com/14804153/43070772-fe0d5bd2-8e70-11e8-8f2a-f74db74f4b1d.png)

I tried to find the error, but without success.

**Comment by nickpettican** [comment]
The most likely cause is that Instagram has changed their backend again, so in function `news_feed_media` [line 122 in instafunctions.py](https://github.com/nickpettican/InstaBot/blob/ab55863af64e5c9e205a5c4ce8027a2ffed11e99/src/instafunctions.py#L122) there's train-wreck, which throws the error and the function returns `False`. Because it's false the bot crashes.
To fix we would have to look at the dictionary returned by [return_sharedData](https://github.com/nickpettican/InstaBot/blob/ab55863af64e5c9e205a5c4ce8027a2ffed11e99/src/instafunctions.py#L85) and change the `news_feed_media` function accordingly so that it can obtain the data needed to populate the `posts` variable that gets returned. To be honest this is bad practice as it crashes the bot, but then again this way we realised that it needs to be updated to adapt to Instagram's changes 👍

**Comment by nickpettican** [comment]
I haven't had the chance to do this, any luck @eliareutlinger?

**Comment by eliareutlinger** [comment]
Actually this error disappeared for me after some time and I got this 400 "Checkpoint required" error again. So I just waited a bit till it should be working again. But today I got a 200 Error response for the first time. Doesn't 200 mean "Everything is OK"?

**Comment by nickpettican** [comment]
Fixed :)
