### ISSUE TITLE
How to apply changes?

### ISSUE THREAD

**Issue by csousougen** [nickpettican/InstaBot#4]
How are the changes in csv and config file, activated? 
Do I have to close and restart the program after any change?

**Comment by nickpettican** [comment]
Hi @csousougen, thanks for the question.

When you make a change to the config file you need to restart the program. 
When you make a change to any of the csv files (tags, tags_to_avoid and friends) the changes will take effect the next day (when the bot wakes up). If you have it set to 24hrs you would need to restart it to take effect.

When I can, I will modify it so that changes in the config file (other than the username and password) will take effect the next day without having to turn the bot off.
