### ISSUE TITLE
Follow / Unfollow List after abnormal iterruption (or Ctrl-C) 

### ISSUE THREAD

**Issue by hoeger** [nickpettican/InstaBot#8]
Hello, I really like the way it's inteended to work. 

**followlist.csv** is being populated while running: 
```
4442366027,1497557029.0
1950604894,1497557211.0
49475988,1497557236.0
```
After Ctrl-C or abnormal interruption, I get this error:

```
Trying to sign in as [...]...  successfully signed in!

Cleaning up last sessions follows...
Error cleaning up: InstaBot instance has no attribute 'clean_up_loop_count'

Successfully logged out!

Thank you for using InstaBot!
```
**followlist.csv** changes to something like this
```
1430829264,0
2313758892,1
3153379750,2
```
**unfollowlist.csv** remains always empty.

It runs again, only if **followlist.csv** is cleared (empty).

**Comment by nickpettican** [comment]
Hi @hoeger and thanks for the feedback.

I fixed the first bug, just a matter of the order in which the **clean_up_loop_count** was initialised.

Turns out I forgot to add the line of code that adds an unfollowed user to the **master_unfollow_list** in the **profile** class that then gets saved as **unfollowlist.csv** - it was made to avoid re-following users. That's fixed now too.

And the reason **followlist.csv** has integers as the timestamps (the second column) after restarting it is because they aren't needed anymore, seeing as they are going to be unfollowed in 30 - 60 second intervals.

**Comment by hoeger** [comment]
Thank You!

**Comment by hoeger** [comment]
Thank You! 


P.D. May be preserving timestamp would help avoid very-fast unfollows below than "follow_time_hours" on abnormal interruptions.

**Comment by nickpettican** [comment]
No problem @hoeger.
It wouldn't matter much because InstaBot would unfollow and wait until the current timestamp is bigger than the next unfollow timestamp, so if the user interrupts the script and re-runs the next day the current timestamp would always be higher and InstaBot would not wait. This is why I gave it a 30 - 60 second interval, so far it looks safe and you won't get banned. Although I think I see what you mean, I could make it so that InstaBot creates new timestamps and adds the users to the `"bucket"`, however, this would interfere with the timings... It's doable though.
